import 'dotenv/config';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { spawn,execFileSync } from 'node:child_process';
import { mkdir } from 'node:fs/promises';
import { Pool } from 'pg';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { chromium } from '@playwright/test';
import { hashPassword,verifyPassword } from '../lib/password';
import { configureAdmin } from '../lib/configure-admin';
import { exportSheet } from '../lib/spreadsheet';
async function main(){
 const name=`axl_test_${Date.now()}`;const url=new URL(process.env.DATABASE_URL!);url.pathname='/'+name;
 const control=new Pool({connectionString:process.env.DATABASE_URL});
 await control.query(`CREATE DATABASE "${name}"`);
 const client=new PrismaClient({adapter:new PrismaPg({connectionString:url.toString()})});
 const setupCode=randomBytes(32).toString('hex');
 const childEnv={...process.env,DATABASE_URL:url.toString(),AXL_SETUP_TOKEN:setupCode};
 let server:ReturnType<typeof spawn>|undefined;let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 let serverLog='';let count=0;
 const ok=(condition:unknown,message:string)=>{assert.ok(condition,message);count++;console.log('✓',message)};
 const base='http://localhost:3101';
 async function request(path:string,method='GET',payload?:unknown,cookie=''){
  const response=await fetch(base+'/api/'+path,{method,headers:{Origin:base,'Content-Type':'application/json',Cookie:cookie},...(payload!==undefined?{body:JSON.stringify(payload)}:{})});
  return {response,result:await response.json()};
 }
 try{
  execFileSync('npm',['run','db:migrate'],{env:childEnv,stdio:'pipe'});
  execFileSync('npm',['run','db:seed'],{env:childEnv,stdio:'pipe'});
  const password=randomBytes(24).toString('hex');
  server=spawn('node',['node_modules/next/dist/bin/next','start','--hostname','0.0.0.0','--port','3101'],{env:childEnv,stdio:['ignore','pipe','pipe']});
  server.stdout!.on('data',d=>serverLog+=d);server.stderr!.on('data',d=>serverLog+=d);
  let ready=false;for(let i=0;i<100;i++){try{const r=await fetch(base+'/login');if(r.ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,200))}
  ok(ready,'Servidor de producción responde');
  ok((await request('health')).result.status==='ok','Comprobación de salud confirma conexión PostgreSQL');
  ok((await request('catalog')).response.status===401,'Catálogos requieren sesión');
  const setupPage=await fetch(base+'/setup');ok(setupPage.ok,'Pantalla de activación disponible antes de la primera cuenta');
  ok((await request('setup','POST',{token:'incorrect',email:'admin@example.test',fullName:'Administrador de prueba',password})).response.status===401,'Activación rechaza códigos incorrectos');
  const setup=await request('setup','POST',{token:setupCode,email:'admin@example.test',fullName:'Administrador de prueba',password});
  ok(setup.response.status===201,'Código privado permite activar la primera cuenta ADMIN');
  const admin=await client.user.findUniqueOrThrow({where:{email:'admin@example.test'}});
  ok(admin.role==='ADMIN'&&setup.response.headers.get('set-cookie')?.includes('HttpOnly'),'Activación crea sesión segura y rol ADMIN');
  ok((await request('setup','POST',{token:setupCode,email:'other@example.test',fullName:'Otra cuenta',password})).response.status===404,'Activación no puede reutilizarse ni reemplazar cuentas');
  const redirectPage=await fetch(base+'/setup',{redirect:'manual'});ok(redirectPage.status===307&&redirectPage.headers.get('location')==='/login','Pantalla de activación cerrada después de crear cuenta');
  ok(await configureAdmin(client,undefined,undefined)===false,'Configuración administrativa no crea cuentas sin variables');
  await assert.rejects(()=>configureAdmin(client,'admin','invalid'));count++;
  const shortPassword=randomBytes(2).toString('hex');const operatorHash=hashPassword(shortPassword);
  ok(await configureAdmin(client,'Admin',operatorHash),'Operador configura una cuenta con usuario corto');
  const operator=await client.user.findUniqueOrThrow({where:{email:'admin'}});
  ok(operator.role==='ADMIN'&&operator.active&&verifyPassword(shortPassword,operator.passwordHash),'Cuenta configurada guarda hash y permisos ADMIN');
  ok(await configureAdmin(client,'admin',operatorHash)===false,'Reiniciar no reconfigura una cuenta idéntica');
  const operatorLogin=await request('login','POST',{email:'admin',password:shortPassword});
  ok(operatorLogin.response.ok,'Inicio de sesión acepta usuario sin correo y contraseña elegida por el operador');
  const operatorCookie=operatorLogin.response.headers.get('set-cookie')!.split(';')[0];
  ok((await request('users','GET',undefined,operatorCookie)).response.ok,'Cuenta configurada accede a administración de usuarios');
  ok(await configureAdmin(client,'admin',hashPassword(shortPassword)),'Cambiar configuración revoca sesiones anteriores');
  ok((await request('users','GET',undefined,operatorCookie)).response.status===401,'Sesiones anteriores quedan revocadas');
  const operatorAudit=await client.auditLog.findMany({where:{recordId:operator.id}});
  ok(!JSON.stringify(operatorAudit).includes(operatorHash),'Auditoría de configuración no contiene hashes');
  ok((await client.user.findUniqueOrThrow({where:{id:admin.id}})).passwordHash===admin.passwordHash,'Configurar usuario conserva las demás cuentas');
  const dispatcher=await client.user.create({data:{email:'dispatch@example.test',fullName:'Despachador de prueba',passwordHash:hashPassword(password),role:'DISPATCHER'}});
  const reader=await client.user.create({data:{email:'read@example.test',fullName:'Consulta de prueba',passwordHash:hashPassword(password),role:'READ_ONLY'}});
  const login=async(email:string)=>{const r=await request('login','POST',{email,password});ok(r.response.ok,'Inicio de sesión '+email+' ('+r.response.status+': '+JSON.stringify(r.result)+')');ok(r.response.headers.get('set-cookie')?.includes('HttpOnly'),'Cookie de sesión HttpOnly');return r.response.headers.get('set-cookie')!.split(';')[0]};
  const adminCookie=await login(admin.email), dispatchCookie=await login(dispatcher.email),readCookie=await login(reader.email);
  const cat=(await request('catalog','GET',undefined,adminCookie)).result;
  ok(cat.tractors.length===11&&cat.trailers.length===21&&cat.destinations.length===1,'Datos maestros completos');
  const result=(await request('dispatch','POST',{command:'t15 axl4416 Houston'},dispatchCookie)).result;
  ok(result.success&&result.formattedText.includes('4WS4416CA')&&result.formattedText.endsWith('HOUSTON, TX 77040-4857'),'Despacho completo consultado desde PostgreSQL');
  ok((await request('dispatch','POST',{command:'T21 3178 Ontario'},dispatchCookie)).result.message==='No registrado.','Ontario sin dirección rechaza sin inventar');
  ok((await request('dispatch','POST',{command:'T14 VACÍO'},dispatchCookie)).result.formattedText.includes('Estado: Vacío'),'Despacho de unidad vacía');
  ok((await request('dispatch','POST',{command:'T15 4416'},readCookie)).response.status===403,'LECTURA no genera despachos');
  ok((await request('tractors','POST',{},dispatchCookie)).response.status===403,'DESPACHADOR no cambia catálogo');
  ok((await request('users','GET',undefined,dispatchCookie)).response.status===403,'Usuarios restringidos a ADMIN');
  ok((await request('history','GET',undefined,readCookie)).response.status===403,'Historial restringido a ADMIN');
  const csrf=await fetch(base+'/api/dispatch',{method:'POST',headers:{Origin:'https://other.example',Cookie:adminCookie,'Content-Type':'application/json'},body:'{"command":"T15"}'});
  ok(csrf.status===403,'Origen ajeno rechazado');
  const t15=cat.tractors.find((t:any)=>t.economicNumber==='T-15');
  const tractorData={...t15,notes:'Actualización de prueba',plateUs:'TEST15CA'};
  ok((await request('tractors/'+t15.id,'PATCH',tractorData,adminCookie)).response.ok,'ADMIN actualiza unidad');
  const history=(await request('history','GET',undefined,adminCookie)).result;
  ok(history.some((h:any)=>h.generatedText.includes('ZP63592CA')&&h.snapshot.tractorPlate==='ZP63592CA'),'Historial conserva placa original tras edición');
  const audit=(await request('audit','GET',undefined,adminCookie)).result;
  ok(audit.some((a:any)=>a.before?.plateUs==='ZP63592CA'&&a.after.plateUs==='TEST15CA'),'Auditoría conserva antes y después');
  execFileSync('npm',['run','db:seed'],{env:childEnv,stdio:'pipe'});
  ok((await client.tractor.findUnique({where:{id:t15.id}}))!.plateUs==='TEST15CA','Seed repetido respeta datos vigentes');
  const tripData={date:'2026-10-06',tractorNumber:'T15',driverName:t15.driver.fullName,trailerNumber:'4416',origin:'Origen capturado',destination:'Destino capturado',status:'Programado',client:'Cliente capturado'};
  const trip=await request('trips','POST',tripData,dispatchCookie);
  ok(trip.response.status===201,'Despachador crea viaje persistente');
  ok((await request('trips','GET',undefined,readCookie)).result.some((t:any)=>t.id===trip.result.id),'LECTURA consulta viajes guardados');
  ok((await request('trips/'+trip.result.id,'PATCH',{...tripData,status:'Completado'},readCookie)).response.status===403,'LECTURA no edita viajes');
  ok((await request('trips/'+trip.result.id,'PATCH',{...tripData,status:'En tránsito'},dispatchCookie)).response.ok,'Viaje se puede actualizar');
  ok((await request('trips','POST',{...tripData,trailerNumber:'invalid'},dispatchCookie)).response.status===400,'Remolque inválido no se convierte silenciosamente en vacío');
  const dest={name:'Ontario',formattedAddress:'Dirección ficticia exclusiva de la base de pruebas',aliases:['Ontario Test'],active:true};
  const destination=await request('destinations','POST',dest,adminCookie);
  ok(destination.response.status===201,'ADMIN crea destino con alias');
  ok((await request('destinations','POST',{...dest,name:'Otro',aliases:['ontario test']},adminCookie)).response.status===400,'Alias ambiguo rechazado');
  ok((await request('dispatch','POST',{command:'T21 3178 ONTARIO TEST'},dispatchCookie)).result.success,'Alias exacto resuelve destino registrado');
  for(let i=0;i<10;i++)await request('login','POST',{email:'missing@example.test',password:'incorrect'});
  ok((await request('login','POST',{email:'missing@example.test',password:'incorrect'})).response.status===429,'Límite de intentos de inicio de sesión');
  const buffer=await exportSheet([{...dest,aliases:'Ontario Test'}],'xlsx',['name','formattedAddress','aliases','active']) as Uint8Array;
  const form=new FormData();form.set('entity','destinations');form.set('file',new File([Buffer.from(buffer)],'destinos.xlsx'));
  const previewResponse=await fetch(base+'/api/import/preview',{method:'POST',headers:{Origin:base,Cookie:adminCookie},body:form});const preview=await previewResponse.json();
  ok(previewResponse.ok&&preview.rows[0].action.startsWith('Actualizar'),'Importación muestra duplicado antes de aplicar');
  ok((await request('import/confirm','POST',{batchId:preview.batchId},adminCookie)).response.status===400,'Importación exige confirmación explícita');
  ok((await request('import/confirm','POST',{batchId:preview.batchId,confirm:true},adminCookie)).result.count===1,'Importación confirmada se aplica');
  const batch=await client.importBatch.findUnique({where:{id:preview.batchId}});
  ok(Array.isArray(batch?.backup)&&!!batch?.confirmedAt,'Respaldo anterior y autor de importación guardados');
  ok((await request('import/confirm','POST',{batchId:preview.batchId,confirm:true},adminCookie)).response.status===400,'Importación no puede aplicarse dos veces');
  const secondPreview=await fetch(base+'/api/import/preview',{method:'POST',headers:{Origin:base,Cookie:adminCookie},body:form});const stale=await secondPreview.json();
  await request('destinations/'+destination.result.id,'PATCH',{...dest,notes:'Cambio concurrente'},adminCookie);
  ok((await request('import/confirm','POST',{batchId:stale.batchId,confirm:true},adminCookie)).response.status===400,'Importación rechaza vista previa desactualizada');
  const exportResponse=await fetch(base+'/api/export?entity=history&format=csv',{headers:{Cookie:adminCookie}});ok(exportResponse.ok&&(await exportResponse.text()).includes('rawCommand'),'Historial exportable en CSV');
  const noExport=await fetch(base+'/api/export?entity=tractors',{headers:{Cookie:readCookie}});ok(noExport.status===403,'Exportación masiva solo ADMIN');
  const users=(await request('users','GET',undefined,adminCookie)).result;ok(users.every((u:any)=>!('passwordHash'in u)),'API y exportaciones no revelan hashes de contraseña');
  ok((await request('users/'+admin.id,'PATCH',{email:admin.email,fullName:admin.fullName,role:'READ_ONLY',active:true},adminCookie)).response.status===400,'ADMIN no pierde acceso por cambiar su propio rol');
  browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox'],headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1050}});const consoleErrors:string[]=[];page.on('pageerror',e=>consoleErrors.push(e.message));
  await page.goto(base+'/login');await page.getByLabel('Usuario o correo').fill(admin.email);await page.getByLabel('Contraseña',{exact:true}).fill(password);await page.getByRole('button',{name:'Ingresar'}).click();
  await page.getByRole('heading',{name:'Todo listo para salir.'}).waitFor();await page.getByLabel('Unidad + remolque + destino (opcional)').fill('T-15 4416 Houston');await page.getByRole('button',{name:'Generar despacho'}).click();await page.locator('.result').filter({hasText:'TEST15CA'}).waitFor();
  ok(await page.locator('.result').innerText().then(t=>t.includes('Houston')||t.includes('HOUSTON')),'Navegador genera y muestra el mensaje');
  await mkdir('/workspace/artifacts',{recursive:true});await page.screenshot({path:'/workspace/artifacts/axl-despacho-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Viajes por día',exact:true}).click();await page.getByRole('button',{name:'Agregar viaje'}).click();await page.getByLabel('Día del viaje').fill('2026-10-07');await page.getByLabel('Unidad',{exact:true}).selectOption('T-15');await page.getByLabel('Destino',{exact:true}).fill('Viaje desde navegador');await page.getByRole('button',{name:'Guardar cambios'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByLabel('Día de los viajes').fill('2026-10-07');await page.getByRole('cell',{name:'Viaje desde navegador'}).waitFor();ok(true,'Formulario de viajes guarda y filtra por día');
  await page.screenshot({path:'/workspace/artifacts/axl-viajes-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Unidades',exact:true}).click();await page.getByRole('cell',{name:'T-15',exact:true}).waitFor();await page.getByRole('row').filter({has:page.getByRole('cell',{name:'T-15',exact:true})}).getByRole('button',{name:'Editar'}).click();await page.getByLabel('Notas',{exact:true}).fill('Editado desde navegador');await page.getByRole('button',{name:'Guardar cambios'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});ok(true,'Formulario administrativo edita una unidad');
  const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await mobile.goto(base+'/login');await mobile.getByLabel('Usuario o correo').fill(dispatcher.email);await mobile.getByLabel('Contraseña',{exact:true}).fill(password);await mobile.getByRole('button',{name:'Ingresar'}).click();await mobile.getByRole('heading',{name:'Todo listo para salir.'}).waitFor();
  await mobile.screenshot({path:'/workspace/artifacts/axl-despacho-mobile.png',fullPage:true});ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=390),'Interfaz móvil sin desbordamiento horizontal');ok(consoleErrors.length===0,'Navegador sin errores de JavaScript');
  await request('logout','POST',undefined,dispatchCookie);ok((await request('catalog','GET',undefined,dispatchCookie)).response.status===401,'Cerrar sesión invalida el token en servidor');
  console.log(`${count} verificaciones de integración aprobadas. Base de pruebas eliminada al terminar.`);
 }catch(e){console.error('Integración falló. Registro del servidor:',serverLog);throw e}finally{
  await browser?.close();if(server){server.kill('SIGTERM');await new Promise<void>(r=>server!.once('exit',()=>r()))}
  await client.$disconnect();await control.query('SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=$1',[name]);await control.query(`DROP DATABASE "${name}"`);await control.end();
 }
}
main().catch(e=>{console.error(e);process.exitCode=1});
