'use client';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { Entity,entityNames } from '@/lib/validation';
import { normalizeTractor,normalizeTrailer,normalizeDestination } from '@/lib/dispatch';
type Row=Record<string,any>;
type User={id:string;email:string;fullName:string;role:string};
type Field={key:string;label:string;type?:string;required?:boolean;wide?:boolean;options?:string[]};
const fields:Record<Entity,Field[]>={
 tractors:[{key:'economicNumber',label:'Unidad',required:true},{key:'driverId',label:'Operador',type:'driver'},{key:'plateUs',label:'Placa USA'},{key:'plateMex',label:'Placa México'},{key:'brand',label:'Marca'},{key:'year',label:'Año',type:'number'},{key:'vin',label:'VIN'},{key:'notes',label:'Notas',wide:true,type:'textarea'}],
 trailers:[{key:'economicNumber',label:'Económico',required:true},{key:'category',label:'Categoría',options:['dry','reefer','flatbed']},{key:'lengthFt',label:'Longitud (pies)',type:'number',options:['45','48','53']},{key:'plateUs',label:'Placa USA'},{key:'plateMex',label:'Placa México'},{key:'notes',label:'Notas',wide:true,type:'textarea'}],
 drivers:[{key:'fullName',label:'Nombre completo',required:true}],
 destinations:[{key:'name',label:'Nombre',required:true},{key:'aliases',label:'Alias (separados por |)'},{key:'formattedAddress',label:'Dirección completa tal como debe aparecer',type:'textarea',wide:true,required:true},{key:'addressLine1',label:'Dirección línea 1'},{key:'addressLine2',label:'Dirección línea 2'},{key:'city',label:'Ciudad'},{key:'state',label:'Estado'},{key:'postalCode',label:'ZIP'},{key:'country',label:'País'},{key:'notes',label:'Notas',type:'textarea',wide:true}],
 users:[{key:'fullName',label:'Nombre completo',required:true},{key:'email',label:'Correo',type:'email',required:true},{key:'role',label:'Rol',options:['ADMIN','DISPATCHER','READ_ONLY']},{key:'password',label:'Contraseña nueva (mínimo 12 caracteres)',type:'password'}],
 settings:[{key:'companyName',label:'Compañía',required:true},{key:'caat',label:'CAAT',required:true},{key:'scac',label:'SCAC',required:true},{key:'timezone',label:'Zona horaria',required:true},{key:'morningGreeting',label:'Saludo antes de las 12:00',required:true},{key:'afternoonGreeting',label:'Saludo desde las 12:00',required:true}],
 trips:[{key:'date',label:'Día del viaje',type:'date',required:true},{key:'tractorNumber',label:'Unidad',type:'tractor',required:true},{key:'driverName',label:'Operador (según unidad)',required:true},{key:'trailerNumber',label:'Remolque (opcional)',type:'trailer'},{key:'origin',label:'Origen'},{key:'destination',label:'Destino',required:true},{key:'client',label:'Cliente'},{key:'reference',label:'Referencia'},{key:'status',label:'Estado',options:['Programado','En tránsito','Completado','Cancelado']},{key:'notes',label:'Notas',type:'textarea',wide:true}]
};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Tijuana',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function api(path:string,options?:RequestInit){const r=await fetch('/api/'+path,{...options,headers:{...(options?.body instanceof FormData?{}:{'Content-Type':'application/json'}),...options?.headers}});const result=await r.json();if(!r.ok)throw new Error(result.message||'No se pudo completar la operación.');return result}
const cols:Record<string,[string,string][]>={
 tractors:[['economicNumber','Unidad'],['driver','Operador'],['plateUs','Placa USA'],['brand','Marca'],['year','Año'],['vin','VIN'],['active','Estado']],
 trailers:[['economicNumber','Económico'],['displayType','Equipo'],['plateUs','Placa USA'],['plateMex','Placa México'],['active','Estado']],
 drivers:[['fullName','Operador'],['active','Estado']],
 destinations:[['name','Destino'],['formattedAddress','Dirección'],['aliases','Alias'],['active','Estado']],
 users:[['fullName','Nombre'],['email','Correo'],['role','Rol'],['active','Estado']],
 trips:[['date','Día'],['tractorNumber','Unidad'],['driverName','Operador'],['trailerNumber','Remolque'],['origin','Origen'],['destination','Destino'],['client','Cliente'],['reference','Referencia'],['status','Estado'],['notes','Notas']],
 history:[['createdAt','Fecha'],['user','Usuario'],['rawCommand','Comando'],['status','Resultado']],
 audit:[['createdAt','Fecha'],['userId','Usuario ID'],['entity','Módulo'],['recordId','Registro']]
};
export default function Dashboard({user}:{user:User}){
 const [section,setSection]=useState('dispatch');const [catalog,setCatalog]=useState<Row>({tractors:[],trailers:[],destinations:[],drivers:[],settings:{}});
 const [rows,setRows]=useState<Row[]>([]);const [stats,setStats]=useState<Row>({});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [command,setCommand]=useState('');const [output,setOutput]=useState('');const [country,setCountry]=useState('US');const [busy,setBusy]=useState(false);
 const [filter,setFilter]=useState('');const [search,setSearch]=useState('');const [tripDate,setTripDate]=useState(today);const [category,setCategory]=useState('');const [edit,setEdit]=useState<Row|null>(null);
 const [importPreview,setImportPreview]=useState<Row|null>(null);const [historyDetail,setHistoryDetail]=useState<Row|null>(null);
 const admin=user.role==='ADMIN';const editable=admin||(user.role==='DISPATCHER'&&section==='trips');
 const refresh=useCallback(async()=>{
  setLoading(true);setError('');
  try{const [c,s]=await Promise.all([api('catalog'),api('statistics')]);setCatalog(c);setStats(s);if(section!=='dispatch')setRows(await api(section));}catch(e){setError(e instanceof Error?e.message:'Error de conexión.')}finally{setLoading(false)}
 },[section]);
 useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{setCategory('');setEdit(null);setImportPreview(null);setNotice('');setHistoryDetail(null)},[section]);
 const navigation=[['dispatch','◎','Despacho'],['trips','▦','Viajes por día'],['tractors','▣','Unidades'],['trailers','▱','Remolques'],['drivers','◉','Operadores'],['destinations','⌖','Destinos'],...(admin?[['history','↺','Historial'],['audit','≡','Auditoría'],['users','♙','Usuarios'],['settings','⚙','Configuración']]:[])];
 const visibleRows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(filter.toLowerCase())&&(section!=='trips'||(!tripDate||r.date===tripDate))&&(section!=='trailers'||!category||r.category===category));
 const results=useMemo(()=>!search.trim()?[]:['tractors','trailers','destinations','drivers'].flatMap(entity=>catalog[entity].filter((r:Row)=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())).map((r:Row)=>({entity,row:r}))).slice(0,20),[catalog,search]);
 const suggestions=useMemo(()=>{
  const tokens=command.split(/\s+/);const prefix=tokens.at(-1)||'';
  if(tokens.length===1)return catalog.tractors.filter((t:Row)=>t.active&&t.economicNumber.replace('-','').toLowerCase().startsWith(prefix.replace('-','').toLowerCase())).map((t:Row)=>t.economicNumber);
  if(tokens.length===2)return catalog.trailers.filter((t:Row)=>t.active&&(t.economicNumber.toLowerCase().startsWith(prefix.toLowerCase())||t.economicNumber.replace('AXL-','').startsWith(prefix))).map((t:Row)=>`${tokens[0]} ${t.economicNumber}`);
  return catalog.destinations.filter((d:Row)=>d.active&&normalizeDestination(d.name).startsWith(normalizeDestination(tokens.slice(2).join(' ')))).map((d:Row)=>`${tokens[0]} ${tokens[1]} ${d.name}`);
 },[command,catalog]);
 async function generate(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await api('dispatch',{method:'POST',body:JSON.stringify({command,plateCountry:country})});setOutput(r.formattedText||r.message);setStats(await api('statistics'))}catch(e){setError(e instanceof Error?e.message:'Error de conexión.')}finally{setBusy(false)}}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setNotice('Mensaje copiado.')}catch{setError('No se pudo copiar. Selecciona el texto y cópialo manualmente.')}}
 function startEdit(row?:Row){setError('');setEdit(row?{...row,aliases:row.aliases?.map((a:Row)=>a.alias).join(' | ')}:{active:true,date:tripDate||today(),category:'dry',lengthFt:53,status:'Programado',role:'READ_ONLY'})}
 async function save(e:React.FormEvent){e.preventDefault();if(!edit)return;setBusy(true);setError('');try{
  const payload:Row={active:edit.active??true};
  for(const field of fields[section as Entity]){let value=edit[field.key];if(field.type==='number')value=value===''||value==null?null:Number(value);else if(field.key==='aliases')value=String(value||'').split('|').map(v=>v.trim()).filter(Boolean);else if(field.key==='password'){if(!value)continue}else value=value===''||value==null?null:String(value);payload[field.key]=value}
  await api(section+(edit.id?'/'+edit.id:''),{method:edit.id?'PATCH':'POST',body:JSON.stringify(payload)});setEdit(null);setNotice('Cambios guardados.');await refresh();
 }catch(e){setError(e instanceof Error?e.message:'Error al guardar.')}finally{setBusy(false)}}
 function change(field:Field,value:string){setEdit(current=>{if(!current)return current;const updated={...current,[field.key]:value};if(field.key==='tractorNumber'){const tractor=catalog.tractors.find((t:Row)=>t.economicNumber===value);updated.driverName=tractor?.driver?.fullName||''}return updated})}
 async function importFile(file:File){setBusy(true);setError('');setImportPreview(null);try{const form=new FormData();form.set('entity',section);form.set('file',file);setImportPreview(await api('import/preview',{method:'POST',body:form}))}catch(e){setError(e instanceof Error?e.message:'Error al importar.')}finally{setBusy(false)}}
 async function confirmImport(){setBusy(true);setError('');try{const result=await api('import/confirm',{method:'POST',body:JSON.stringify({batchId:importPreview?.batchId,confirm:true})});setImportPreview(null);setNotice(`${result.count} registros guardados. Respaldo y auditoría conservados.`);await refresh()}catch(e){setError(e instanceof Error?e.message:'Error al importar.')}finally{setBusy(false)}}
 function display(row:Row,key:string){const v=row[key];if(key==='active')return <span className={'badge '+(!v?'off':'')}>{v?'Activo':'Inactivo'}</span>;if(key==='driver')return v?.fullName||'No registrado.';if(key==='user')return v?.fullName||'—';if(key==='aliases')return v?.map((a:Row)=>a.alias).join(', ')||'—';if(key==='createdAt')return new Date(v).toLocaleString('es-MX',{timeZone:'America/Tijuana'});if(key==='formattedAddress')return <pre>{v}</pre>;if(key==='status')return <span className="badge">{v}</span>;return v??'—'}
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/">AXL<span>TRANSPORT</span></a><p className="eyebrow">CENTRO DE OPERACIONES</p><nav>{navigation.map(([key,icon,label])=><button key={key} className={section===key?'selected':''} onClick={()=>{setFilter('');setSection(key)}}><span className="nav-icon" aria-hidden="true">{icon}</span>{label}</button>)}</nav><div className="sidebar-footer"><p>{user.fullName}</p><p className="muted">{admin?'Administrador':user.role==='DISPATCHER'?'Despachador':'Solo lectura'}</p><button onClick={async()=>{try{await api('logout',{method:'POST'});window.location.assign('/login')}catch{setError('No se pudo cerrar sesión.')}}}>Cerrar sesión ↗</button></div></aside>
 <div className="workspace"><header className="topbar"><span className="mobile-brand">AXL</span><span className="muted">Operaciones / {section==='dispatch'?'Despacho':entityNames[section as Entity]||navigation.find(n=>n[0]===section)?.[2]}</span><input aria-label="Buscar unidades, operadores, placas y destinos" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar unidad, operador, placa o destino…"/><span className="status">CAAT 43E8 · SCAC AJXT</span></header><main className="content">
 <div className="heading"><div><p className="eyebrow muted">AXL TRANSPORT DISPATCH</p><h1>{section==='dispatch'?'Todo listo para salir.':section==='trips'?'Viajes por día':entityNames[section as Entity]||navigation.find(n=>n[0]===section)?.[2]}</h1><p className="muted">{section==='dispatch'?'Genera los datos de tu despacho en segundos.':section==='trips'?'Organiza la operación, un día a la vez.':'Consulta y administra tu información registrada.'}</p></div><div className="date-label">{new Date().toLocaleDateString('es-MX',{timeZone:'America/Tijuana',weekday:'long',day:'numeric',month:'long',year:'numeric'})}<br/><span className="badge">America/Tijuana</span></div></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {search&&<section className="panel search-results"><div className="panel-head"><h3>Resultados de búsqueda</h3><button onClick={()=>setSearch('')}>Cerrar</button></div>{results.length?<div className="table-scroll"><table><tbody>{results.map(({entity,row})=><tr key={row.id}><td>{entityNames[entity as Entity]}</td><td>{row.economicNumber||row.name||row.fullName}</td><td>{row.driver?.fullName||row.displayType||row.formattedAddress}</td><td><button onClick={()=>{setSection(entity);setFilter(row.economicNumber||row.name||row.fullName);setSearch('')}}>Ver módulo</button></td></tr>)}</tbody></table></div>:<div className="empty">Sin coincidencias.</div>}</section>}
 {loading?<div className="loading">Cargando información registrada…</div>:section==='dispatch'?<>
 <div className="stats">{[['Unidades activas',stats.tractors,'Flota registrada'],['Remolques activos',stats.trailers,'Equipos disponibles'],['Destinos',stats.destinations,'Direcciones registradas'],['Despachos hoy',stats.today,'Hora de Tijuana']].map(([label,count,note])=><div className="stat" key={String(label)}><span>{label}</span><strong>{count??0}</strong><small>{note}</small></div>)}</div>
 <div className="dispatch-grid"><section className="panel"><div className="panel-head"><h3>Nuevo despacho</h3><span className="badge">Consulta directa</span></div><div className="panel-body"><form className="command-form" onSubmit={generate}><label htmlFor="command">Unidad + remolque + destino (opcional)</label><input id="command" list="commands" className="command-input" placeholder="T-15 4416 Houston" value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{if(e.key==='Escape'){setCommand('');setOutput('')}}} autoComplete="off" maxLength={500} required/><datalist id="commands">{suggestions.map((s:string)=><option key={s} value={s}/>)}</datalist><label>Placas a utilizar<select value={country} onChange={e=>setCountry(e.target.value)}><option value="US">Estados Unidos (estándar)</option><option value="MX">México (solicitud explícita)</option></select></label><button className="primary" style={{marginTop:16}} disabled={busy||user.role==='READ_ONLY'}>{busy?'Consultando…':'Generar despacho →'}</button></form><div className="examples"><span className="muted" style={{width:'100%',fontSize:11}}>PRUEBA UN COMANDO</span>{['T-15 4416','T-14 vacío','T-16 4069 Houston','T-17 R2'].map(s=><button key={s} onClick={()=>setCommand(s)}>{s}</button>)}</div><p className="section-note">Enter para generar · Escape para limpiar<br/>Si falta información indispensable, el resultado será “No registrado.”{user.role==='READ_ONLY'&&<><br/>Tu cuenta permite consultar catálogos; la generación requiere rol de despachador.</>}</p></div></section>
 <section className="panel"><div className="panel-head"><h3>Mensaje de despacho</h3><button className="secondary" disabled={!output} onClick={()=>copy(output)}>Copiar mensaje ↗</button></div><div className="panel-body">{output?<pre className="result">{output}</pre>:<div className="result-empty"><div><div className="symbol">▤</div><strong>Tu mensaje aparecerá aquí</strong>Escribe un comando y genera el despacho.<br/>Listo para copiar, con el formato oficial.</div></div>}<p className="section-note">Información obtenida exclusivamente de los registros de AXL Transport.</p></div></section></div>
 </>:<>
 {section==='trips'&&<p className="trip-help">Esta tabla guarda los viajes en la base de datos. Sus columnas iniciales se ajustarán al ejemplo de Excel que compartas. La unidad seleccionada aporta el operador registrado; origen, cliente y destino se capturan para cada viaje.</p>}
 <div className="toolbar"><input aria-label="Filtrar registros" placeholder="Filtrar registros…" value={filter} onChange={e=>setFilter(e.target.value)}/>{section==='trips'&&<label>Día<input aria-label="Día de los viajes" type="date" value={tripDate} onChange={e=>setTripDate(e.target.value)}/></label>}{section==='trailers'&&<select style={{width:160}} aria-label="Categoría" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todos los equipos</option><option value="dry">Cajas secas</option><option value="reefer">Refrigeradas</option><option value="flatbed">Plataformas</option></select>}{editable&&section in fields&&section!=='settings'&&<button className="primary" onClick={()=>startEdit()}>+ {section==='trips'?'Agregar viaje':'Agregar registro'}</button>}{admin&&section!=='audit'&&section!=='settings'&&<><a href={`/api/export?entity=${section}&format=csv`}>Exportar CSV</a><a href={`/api/export?entity=${section}&format=xlsx`}>Exportar Excel</a></>}{admin&&['tractors','trailers','drivers','destinations'].includes(section)&&<><a href={`/api/export?entity=${section}&template=1`}>Plantilla Excel</a><label><span className="badge">Importar Excel</span><input aria-label="Importar Excel" type="file" accept=".xlsx" disabled={busy} onChange={e=>{if(e.target.files?.[0])void importFile(e.target.files[0]);e.target.value=''}}/></label></>}</div>
 {section==='settings'?<section className="panel"><div className="panel-body">{rows[0]&&<><h3>Configuración de despacho</h3>{fields.settings.map(f=><p key={f.key}><span className="muted">{f.label}: </span>{rows[0][f.key]}</p>)}<button className="primary" onClick={()=>startEdit(rows[0])}>Editar configuración</button></>}</div></section>:<section className="panel"><div className="table-scroll"><table><thead><tr>{cols[section]?.map(([key,label])=><th key={key}>{label}</th>)}<th>Acciones</th></tr></thead><tbody>{visibleRows.map(row=><tr key={row.id}>{cols[section]?.map(([key])=><td key={key}>{display(row,key)}</td>)}<td>{editable&&section in fields&&<button onClick={()=>startEdit(row)}>Editar</button>}{section==='destinations'&&<button onClick={()=>copy(row.formattedAddress)}>Copiar</button>}{(section==='history'||section==='audit')&&<button onClick={()=>setHistoryDetail(row)}>Ver detalle</button>}</td></tr>)}</tbody></table>{!visibleRows.length&&<div className="empty">No hay registros para esta selección.</div>}</div></section>}
 {(section==='history'||section==='audit')&&<p className="section-note">Se muestran los últimos 500 registros.{section==='history'&&' La exportación incluye todo el historial.'}</p>}
 </>}
 {edit&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="form-title"><h2 id="form-title">{edit.id?'Editar':'Agregar'} · {entityNames[section as Entity]}</h2><p className="muted">Los cambios quedan registrados en la auditoría.</p>{error&&<p className="error" role="alert">{error}</p>}<form onSubmit={save}><div className="form-grid">{fields[section as Entity].map(field=><label key={field.key} className={field.wide?'wide':''}>{field.label}{field.type==='textarea'?<textarea aria-label={field.label} required={field.required} value={edit[field.key]??''} onChange={e=>change(field,e.target.value)}/>:field.options||['driver','tractor','trailer'].includes(field.type||'')?<select aria-label={field.label} required={field.required} value={edit[field.key]??''} onChange={e=>change(field,e.target.value)}>{!field.options&&<option value="">Seleccionar…</option>}{(field.options||catalog[field.type==='driver'?'drivers':field.type==='tractor'?'tractors':'trailers'].filter((r:Row)=>r.active)).filter((r:Row|string,i:number,a:(Row|string)[])=>typeof r==='string'||a.findIndex(x=>typeof x!=='string'&&x.id===r.id)===i).map((r:string|Row)=>{const val=typeof r==='string'?r:field.type==='driver'?r.id:r.economicNumber;return <option key={val} value={val}>{typeof r==='string'?({dry:'Caja seca',reefer:'Refrigerada',flatbed:'Plataforma'} as Row)[r]||r:field.type==='driver'?r.fullName:r.economicNumber}</option>})}</select>:<input aria-label={field.label} type={field.type||'text'} required={field.required||(field.key==='password'&&!edit.id)} minLength={field.key==='password'?12:undefined} autoComplete={field.key==='password'?'new-password':'off'} value={edit[field.key]??''} readOnly={section==='trips'&&field.key==='driverName'} onChange={e=>change(field,e.target.value)}/>}</label>)}{section!=='settings'&&<label>Estado del registro<select value={edit.active?'true':'false'} onChange={e=>setEdit({...edit,active:e.target.value==='true'})}><option value="true">Activo</option><option value="false">Inactivo (conservar historial)</option></select></label>}</div><div className="actions"><button type="button" onClick={()=>{setEdit(null);setError('')}}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar cambios'}</button></div></form></section></div>}
 {historyDetail&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Detalle histórico"><h2>Detalle histórico</h2>{section==='history'?<><pre className="result">{historyDetail.generatedText}</pre><button onClick={()=>copy(historyDetail.generatedText)}>Copiar</button><details className="details"><summary>Datos conservados en el despacho</summary><pre>{JSON.stringify(historyDetail.snapshot,null,2)}</pre></details></>:<><h3>Antes</h3><pre>{JSON.stringify(historyDetail.before,null,2)}</pre><h3>Después</h3><pre>{JSON.stringify(historyDetail.after,null,2)}</pre></>}<div className="actions"><button onClick={()=>setHistoryDetail(null)}>Cerrar</button></div></section></div>}
 {importPreview&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Revisar importación"><h2>Revisar importación</h2><p>Revisa cada registro antes de confirmar. Los económicos existentes están marcados como actualización. Se conservará un respaldo completo del módulo antes de aplicar los cambios.</p>{error&&<p className="error">{error}</p>}<div className="table-scroll"><table><thead><tr><th>Acción</th><th>Registro propuesto</th></tr></thead><tbody>{importPreview.rows.map((r:Row,i:number)=><tr key={i}><td>{r.action}</td><td><pre>{JSON.stringify(r,null,2)}</pre></td></tr>)}</tbody></table></div><div className="actions"><button onClick={()=>setImportPreview(null)}>Cancelar</button><button className="primary" disabled={busy} onClick={confirmImport}>Confirmar {importPreview.rows.length} cambios</button></div></section></div>}
 </main></div></div>
}
