import 'dotenv/config';
import { Pool } from 'pg';
import { readdir,readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
// Apply the SQL generated by Prisma's verified WASM schema engine. The 6.x
// experimental migration adapter cannot deserialize PostgreSQL catalog NAME
// columns. This transactional runner uses pg directly and verifies saved hashes.
async function main(){
 if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL no está configurada. Agrégala en Environment del servicio.");
 const pool=new Pool({connectionString:process.env.DATABASE_URL});const client=await pool.connect();
 try{
  await client.query('BEGIN');
  await client.query('SELECT pg_advisory_xact_lock(43884388)');
  await client.query('CREATE TABLE IF NOT EXISTS public._axl_migrations (name TEXT PRIMARY KEY, checksum TEXT NOT NULL, applied_at TIMESTAMPTZ NOT NULL DEFAULT now())');
  const dirs=(await readdir('prisma/migrations',{withFileTypes:true})).filter(d=>d.isDirectory()).map(d=>d.name).sort();
  for(const name of dirs){
   const sql=await readFile(`prisma/migrations/${name}/migration.sql`,'utf8');
   const checksum=createHash('sha256').update(sql).digest('hex');
   const existing=await client.query('SELECT checksum FROM public._axl_migrations WHERE name=$1',[name]);
   if(existing.rows.length){if(existing.rows[0].checksum!==checksum)throw new Error(`Migración modificada después de aplicar: ${name}`);continue}
   await client.query(sql);
   await client.query('INSERT INTO public._axl_migrations(name,checksum) VALUES($1,$2)',[name,checksum]);
   console.log('Migración aplicada:',name);
  }
  await client.query('COMMIT');console.log('Base de datos actualizada.');
 }catch(e){await client.query('ROLLBACK');throw e}finally{client.release();await pool.end()}
}
main().catch(e=>{console.error('Migración fallida:',e instanceof Error?e.message:'Error');process.exitCode=1});
